### ISSUE TITLE
Don't use this thing - It will break your Backend

### ISSUE THREAD

**Issue by janknobloch** [shopwareLabs/SwagTinyMceCustomFont#5]
Not working on sShopware 5.6.6 breaks your whole backend (white screen of death)

no logging to var/log whatsoever.

Fix your backend:
By deleting the plugin from its folder in /custom/plugins
Restart your Backend
Unzip and plugin again in plugins folder and properly remove it via UI uninstall.

**Comment by shyim** [comment]
Hey @janknobloch ,
it has been fixed with the linked commit. Thanks for the reporting! 💙
